Repository bandantonio/obsidian-apple-books-highlights-plugin, pull requests merged in 2024-07, with the labels that each got.

#29 fix: remove new lines around colored highlight blocks
  README.md
Labels: bug, documentation

#36 fix: correct spelling for highlight throughout codebase
  src/db/seedData.ts
  src/settings.ts
  test/db.spec.ts
  test/mocks/aggregatedDetailsData.ts
  test/mocks/renderedTemplate.ts
  test/mocks/testDatabase.sqlite
Labels: bug

#28 fix: remove new lines from the end of contextual text blocks
  src/methods/aggregateDetails.ts
  src/types.ts
  src/utils/index.ts
  src/utils/preserveNewlineIndentation.ts
  src/utils/removeTrailingSpaces.ts
  test/mocks/aggregatedDetailsData.ts
  test/mocks/rawTemplates.ts
  test/mocks/renderedTemplate.ts
  test/removeTrailingSpaces.spec.ts
  test/renderHighlightsTemplate.spec.ts
  test/saveHighlightsToVault.spec.ts
Labels: bug

#37 docs: vitepress configuration. Split docs and readme content
  .github/workflows/docs.yml
  .gitignore
  README.md
  docs/.vitepress/config.mts
  docs/.vitepress/theme/custom.css
  docs/.vitepress/theme/index.js
  docs/assets/colored-highlights.png
  docs/assets/plugin-preview.png
  docs/assets/showcase-dark.png
  docs/assets/showcase-light.png
  docs/customization/templates-and-variables.md
  docs/guide/get-started.md
  docs/guide/settings.md
  docs/index.md
  docs/public/dark.png
  docs/public/light.png
  docs/public/logo.svg
  package-lock.json
  package.json
  plugin-banner.png
  preview.png
  template-colors.png
  test/pluginDocs.spec.ts
Labels: documentation
